name: ai_image_enlarger
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  connectivity_plus:
  cached_network_image:
  get_it:
  get_storage:
  dio:
  http:
  image_picker:
  fluttertoast:
  image_cropper: ^3.0.1
  screenshot:
  image_gallery_saver:
  permission_handler:
  flutter_svg:
#  image_painter: ^0.4.6
  google_fonts:
  vector_math:
  share_plus:
  path_provider:

  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/